theme = "tokyonight_moon"

[editor]
auto-completion = true
auto-save = true
bufferline = "multiple"
color-modes = true
continue-comments = false
cursorline = true
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
C-l = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
C-r = [":reload-all", ":config-reload"]

[keys.insert]
h = { h = "normal_mode" }
