theme = "tokyonight"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-l = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
