# CSS Config
[[language]]
name = "css"
file-types = ["css"]
language-servers = ["vscode-css-languageserver"]
auto-format = true

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]

# HTML Config
[[language]]
name = "html"
file-types = ["html", "htm"]
language-servers = ["vscode-html-languageserver"]
auto-format = true

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]

# JSON Config
[[language]]
name = "json"
file-types = ["json"]
language-servers = ["vscode-json-languageserver"]
auto-format = true

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]

# Markdown Config
[[language]]
name = "markdown"
scope = "source.markdown"
file-types = ["md", "markdown"]
comment-tokens = ["<!--", "-->"]
indent = { tab-width = 2, unit = "  " }
auto-format = true

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]

# Rust Config
[[language]]
name = "rust"
auto-format = true

[language.formatter]
command = "rustfmt"
args = ["--emit", "stdout"]

# TOML Config
[[language]]
name = "toml"
auto-format = true

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]

# Typescript Config
[[language]]
name = "typescript"
auto-format = true

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]
