name = "main"
position = "bottom"
anchor_to_edges = true
exclusive_zone = false
autohide = 800
start_hidden = false
popup_autohide = false
height = 34
popup_gap = 8

[margin]
bottom = 8

[[start]]
type = "workspaces"
favorites = ["1", "2", "3", "4", "5"]
all_monitors = false

[[start]]
type = "music"
format = "{title} - {artist}"
truncate = "end"

[[center]]
type = "script"
name = "focused-title"
mode = "poll"
interval = 500
cmd = "niri msg -j windows | jq -r '.[] | select(.is_focused) | .title'"

[[end]]
type = "tray"
icon_size = 16

[[end]]
type = "inhibit"

[[end]]
type = "clipboard"
max_items = 10

[[end]]
type = "network_manager"
icon_size = 16
types_blacklist = ["loopback", "bridge", "veth", "tun"]

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 100
sink_slider_orientation = "vertical"

[[end]]
type = "clock"
format = "%a %d %b  %H:%M"

[[end]]
type = "sys_info"
format = ["CPU {cpu_percent}%", "MEM {memory_percent}%"]

  [end.interval]
  cpu = 3
  memory = 10
