# Font
font_family      Maple Mono NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.5

# Padding
window_padding_width 4
window_margin_width  2

# Scroll Back
scrollback_lines 10000
scrollback_pager less

# Alerts
enable_audio_bell no
visual_bell_duration 0

# Faster Rendering
repaint_delay 7
input_delay 2

# Transparency
background_opacity 0.97

# Catppuccin Mocha colorscheme
foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #f5e0dc

cursor                #f5e0dc
cursor_text_color     #1e1e2e

# Black
color0   #45475a
color8   #585b70

# Red
color1   #f38ba8
color9   #f38ba8

# Green
color2   #a6e3a1
color10  #a6e3a1

# Yellow
color3   #f9e2af
color11  #f9e2af

# Blue
color4   #89b4fa
color12  #89b4fa

# Magenta
color5   #f5c2e7
color13  #f5c2e7

# Cyan
color6   #94e2d5
color14  #94e2d5

# White
color7   #bac2de
color15  #a6adc8

# Tab bar
tab_bar_background #181825

# No confirmations
confirm_os_window_close 0
paste_actions no-op

enabled_layouts splits,stack,tall,fat,grid

active_border_color   #89b4fa
inactive_border_color #313244

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 1
tab_title_template "{index}: {title}"
active_tab_foreground   #cdd6f4
active_tab_background   #1e1e2e
inactive_tab_foreground #585b70
inactive_tab_background #313244
active_tab_font_style   bold

map ctrl+space>backslash launch --location=vsplit --cwd=current
map ctrl+space>minus     launch --location=hsplit --cwd=current

map alt+left        neighboring_window left
map alt+right       neighboring_window right
map alt+up          neighboring_window up
map alt+down        neighboring_window down

map ctrl+space>h    neighboring_window left
map ctrl+space>j    neighboring_window down
map ctrl+space>k    neighboring_window up
map ctrl+space>l    neighboring_window right

map ctrl+space>left  resize_window narrower 5
map ctrl+space>right resize_window wider 5
map ctrl+space>up    resize_window taller 5
map ctrl+space>down  resize_window shorter 5

map shift+left      previous_tab
map shift+right     next_tab
map ctrl+space>[    previous_tab
map ctrl+space>]    next_tab

map ctrl+space>t new_tab_with_cwd
map ctrl+space>q close_window
map ctrl+space>w close_tab
map ctrl+space>z toggle_layout stack
map ctrl+space>r set_tab_title
map ctrl+space>f5 load_config_file

startup_session ~/.config/kitty/sessions/mainframe.conf

allow_hyperlinks yes
undercurl_style thin-sparse
allow_remote_control yes
listen_on unix:/tmp/kitty

map ctrl+space>p kitten hints
map ctrl+space>u kitten hints --type url --program browser
map ctrl+space>s launch --type=overlay --stdin-source=@screen_scrollback nvim -R -
map ctrl+space>b launch --allow-remote-control kitty +kitten broadcast

map ctrl+space>shift+s save_as_session --use-foreground-process
